src/Entity/Player.php
<?php

namespace App\Entity;

use App\Repository\PlayerRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlayerRepository::class)]
class Player
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 1000)]
    private $photo;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\Column(type: 'integer')]
    private $age;

    #[ORM\Column(type: 'integer')]
    private $size;

    #[ORM\Column(type: 'string', length: 3)]
    private $nationality;

    #[ORM\Column(type: 'string', length: 3)]
    private $position;

    #[ORM\Column(type: 'integer')]
    private $trophies;

    #[ORM\Column(type: 'integer')]
    private $yellow_cards;

    #[ORM\Column(type: 'integer')]
    private $red_cards;

    #[ORM\Column(type: 'integer')]
    private $total_goals;

    #[ORM\Column(type: 'integer')]
    private $total_assists;

    #[ORM\ManyToOne(targetEntity: Club::class, inversedBy: 'player')]
    private $club;

    #[ORM\ManyToOne(targetEntity: National::class, inversedBy: 'player')]
    private $national;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getTrophies(): ?int
    {
        return $this->trophies;
    }

    public function setTrophies(int $trophies): self
    {
        $this->trophies = $trophies;

        return $this;
    }

    public function getYellowCards(): ?int
    {
        return $this->yellow_cards;
    }

    public function setYellowCards(int $yellow_cards): self
    {
        $this->yellow_cards = $yellow_cards;

        return $this;
    }

    public function getRedCards(): ?int
    {
        return $this->red_cards;
    }

    public function setRedCards(int $red_cards): self
    {
        $this->red_cards = $red_cards;

        return $this;
    }

    public function getTotalGoals(): ?int
    {
        return $this->total_goals;
    }

    public function setTotalGoals(int $total_goals): self
    {
        $this->total_assists = $total_goals;

        return $this;
    }

    public function getTotalAssists(): ?int
    {
        return $this->total_assists;
    }

    public function setTotalAssists(int $total_assists): self
    {
        $this->total_assists = $total_assists;

        return $this;
    }

    public function getClub(): ?Club
    {
        return $this->club;
    }

    public function setClub(?Club $club): self
    {
        $this->club = $club;

        return $this;
    }

    public function getNational(): ?National
    {
        return $this->national;
    }

    public function setNational(?National $national): self
    {
        $this->national = $national;

        return $this;
    }
}

src/Form/PlayerType.php
<?php

namespace App\Form;

use App\Entity\Club;
use App\Entity\National;
use App\Entity\Player;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Component\Form\CallbackTransformer;

class PlayerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('photo', TextType::class, ['label' => 'Image url ', 'attr' => array('placeholder' => 'link to png file'),
            'constraints' => [new Assert\Callback([
                'callback' => static function(?string $value, ExecutionContextInterface $context){
                    if(!str_ends_with($value, ".png")){
                        $context
                            ->buildViolation('Url must end by ".png"')
                            ->atPath('[photo]')
                            ->addViolation();
                    }
                }
            ]
            )]])
            ->add('firstname', TextType::class, ['label' => 'First name ', 'attr' => array('placeholder' => 'ex: firstname')])
            ->add('lastname', TextType::class, ['label' => 'Last name ', 'attr' => array('placeholder' => 'ex: lastname')])
            ->add('age', IntegerType::class, ['label' => 'Age ', 'attr' => array('placeholder' => 'ex: 17'),
            'constraints' => [
                new Assert\GreaterThan([
                    'value' => 16,
                    'message' => "Age must be greater than 16"
                ]),
                new Assert\LessThanOrEqual([
                    'value' => 55,
                    'message' => 'Age must be lower or equal to 55'
                ])
            ]])
            ->add('size', IntegerType::class, ['label' => 'Size (cm) ', 'attr' => array('placeholder' => 'ex: 151'),
            'constraints' => [
                new Assert\GreaterThan([
                    'value' => 150,
                    'message' => 'Size must be greater than 150 cm'
                ]),
                new Assert\LessThanOrEqual([
                    'value' => 220,
                    'message' => 'Size must be lower or equal to 220 cm'
                ])
            ]])
            ->add('nationality', TextType::class, ['label' => 'Country birth (put 3 first letters or official initials) ', 'attr' => array('placeholder' => 'ex: NAT')])
            ->add('position', TextType::class, ['label' => 'Position on the pitch (official initials) ', 'attr' => array('placeholder' => 'ex: POS')])
            ->add('trophies', IntegerType::class, ['label' => 'Number of trophies ', 'attr' => array('placeholder' => 'ex: 0'),
            'constraints' => [
                new Assert\PositiveOrZero([
                    'message' => 'Value must be positive or at least equals to 0.'
                ])]])
            ->add('yellow_cards', IntegerType::class, ['label' => 'Number of yellow cards ', 'attr' => array('placeholder' => 'ex: 0'),
            'constraints' => [
                new Assert\PositiveOrZero([
                    'message' => 'Value must be positive or at least equals to 0.'
                ])]])
            ->add('red_cards', IntegerType::class, ['label' => 'Number of red cards ', 'attr' => array('placeholder' => 'ex: 0'),
            'constraints' => [
                new Assert\PositiveOrZero([
                    'message' => 'Value must be positive or at least equals to 0.'
                ])]])
            ->add('total_goals', IntegerType::class, ['label' => 'Number of goals ', 'attr' => array('placeholder' => 'ex: 0'),
            'constraints' => [
                new Assert\PositiveOrZero([
                    'message' => 'Value must be positive or at least equals to 0.'
                ])]])
            ->add('total_assists', IntegerType::class, ['label' => 'Number of assists ', 'attr' => array('placeholder' => 'ex: 0'),
            'constraints' => [
                new Assert\PositiveOrZero([
                    'message' => 'Value must be positive or at least equals to 0.'
                ])]])
            ->add('club', EntityType::class, ['class' => Club::class, 'label' => 'Current club ', 'choice_label' => 'name', 'attr' => array('placeholder' => 'ex: club')])
            ->add('national', EntityType::class, ['class' => National::class, 'label' => 'Country choosen ', 'choice_label' => 'name', 'attr' => array('placeholder' => 'ex: national team')])
        ;

        $builder->get('nationality')
            ->addModelTransformer(new CallbackTransformer(
                function ($lowercase) {
                    // transform uppercase string to lowercase string
                    return strtolower($lowercase);
                },
                function ($uppercase) {
                    // transform lowercase string to uppercase string
                    return strtoupper($uppercase);
                }
            ))
        ;

        $builder->get('position')
            ->addModelTransformer(new CallbackTransformer(
                function ($lowercase) {
                    // transform uppercase string to lowercase string
                    return strtolower($lowercase);
                },
                function ($uppercase) {
                    // transform lowercase string to uppercase string
                    return strtoupper($uppercase);
                }
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Player::class,
        ]);
    }
}

src/Controller/PlayerController.php
<?php

namespace App\Controller;

use App\Entity\Player;
use App\Form\PlayerType;
use App\Repository\PlayerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/player')]
class PlayerController extends AbstractController
{
    #[Route('/', name: 'app_player_index', methods: ['GET'])]
    public function index(PlayerRepository $playerRepository): Response
    {
        return $this->render('player/index.html.twig', [
            'players' => $playerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_player_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PlayerRepository $playerRepository): Response
    {
        $player = new Player();
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $playerRepository->add($player);
            return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('player/new.html.twig', [
            'player' => $player,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_player_show', methods: ['GET'])]
    public function show(Player $player): Response
    {
        return $this->render('player/show.html.twig', [
            'player' => $player,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_player_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Player $player, PlayerRepository $playerRepository): Response
    {
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $playerRepository->add($player);
            return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('player/edit.html.twig', [
            'player' => $player,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_player_delete', methods: ['POST'])]
    public function delete(Request $request, Player $player, PlayerRepository $playerRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$player->getId(), $request->request->get('_token'))) {
            $playerRepository->remove($player);
        }

        return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/player/_delete_form.html.twig
<form method="post" action="{{ path('app_player_delete', {'id': player.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ player.id) }}">
    <button class="btn btn-danger btn-outline-light">Delete</button>
</form>

templates/player/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-outline-light">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/player/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ player.firstname }} {{ player.lastname }}{% endblock %}

{% block body %}
<body style="background-image: url({{ bg }});
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;">

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <h1>Edit player</h1>
            <a class="navbar-brand" href="{{ path('app_player_index') }}">Back</a>
        </div>
    </nav><br>

    {{ include('player/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('player/_delete_form.html.twig') }}
</body>
{% endblock %}

templates/player/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Players{% endblock %}

{% block body %}
<body style="background-image: url({{ bg }});
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;">

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ path('app_index') }}">Home</a>
            <h1>Players</h1>
            <form class="d-flex" action="{{ path('app_player_new') }}">
                <input class="form-control me-2" type="submit" value="New" />
            </form>
        </div>
    </nav><br>  

    <ul class="list-group list-group-horizontal list-group-flush">
        {% for player in players %}
            <li class="list-group-item">
                <div class="card-img-top mx-auto">
                    {% if player.photo is empty %}
                        Unavailable photo
                    {% else %}
                        <img style="width: 50%" class="card-img-top mx-auto" src="{{ player.photo }}"/>
                    {% endif %}
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item bg-transparent">Firstname: {{ player.firstname }}</li>
                        <li class="list-group-item bg-transparent">Lastname: {{ player.lastname }}</li>
                        <li class="list-group-item bg-transparent">Age: {{ player.age }}</li>
                        <li class="list-group-item bg-transparent">Size: {{ player.size }}</li>
                        <li class="list-group-item bg-transparent">Nationality: {{ player.nationality }}</li>
                        <li class="list-group-item bg-transparent">Position: {{ player.position }}</li>
                        <li class="list-group-item bg-transparent">
                            {% if player.club is empty %}
                                No club
                            {% else %}
                                Club: {{ player.club.name }}
                            {% endif %}
                        </li>
                        <li class="list-group-item bg-transparent">
                            {% if player.national is empty %}
                                No national team
                            {% else %}
                                National team: {{ player.national.name }} ({{ player.national.country }})
                            {% endif %}
                        </li>
                        <li class="list-group-item bg-transparent">
                            <div class="d-flex justify-content-center">
                                <form action="{{ path('app_player_show', {'id': player.id}) }}">
                                    <input type="submit" value="View" />
                                </form>
                                <form action="{{ path('app_player_edit', {'id': player.id}) }}">
                                    <input type="submit" value="Edit" />
                                </form>
                            </div>
                        </li>
                    </ul>
                </div>
            </li>
        {% endfor %} 
    </ul>
</body>
{% endblock %}

templates/player/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add player{% endblock %}

{% block body %}
<body style="background-image: url({{ bg }});
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;">

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <h1>Informations about player</h1>
            <a class="navbar-brand" href="{{ path('app_player_index') }}">Back</a>
        </div>
    </nav><br>

    {{ include('player/_form.html.twig') }}
</body>
{% endblock %}

templates/player/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ player.firstname }} {{ player.lastname }}{% endblock %}

{% block body %}
<body style="background-image: url({{ bg }});
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;">

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ path('app_player_index') }}">Back</a>
            <h1>Details</h1>
        </div>
    </nav><br>

    <div class="d-flex flex-column bd-highlight mb-3">
        <div class="p-2 bd-highlight">
            <img width='10%' src="{{ player.photo }}"/>
        </div>
        <div class="p-2 bd-highlight">
            Firstname: {{ player.firstname }}
        </div>
        <div class="p-2 bd-highlight">
            Lastname: {{ player.lastname }}
        </div>
        <div class="p-2 bd-highlight">
            Age: {{ player.age }}
        </div>
        <div class="p-2 bd-highlight">
            Nationality: {{ player.nationality }}
        </div>
        <div class="p-2 bd-highlight">
            Position: {{ player.position }}
        </div>
        <div class="p-2 bd-highlight">
            Number of trophies: {{ player.trophies }}
        </div>
        <div class="p-2 bd-highlight">
            Number of yellow cards: {{ player.yellowCards }}
        </div>
        <div class="p-2 bd-highlight">
            Number of red cards: {{ player.redCards }}
        </div>
        <div class="p-2 bd-highlight">
            Total of scored goals: {{ player.totalGoals }}
        </div>
        <div class="p-2 bd-highlight">
            Total of assists: {{ player.totalAssists }}
        </div>
        <div class="p-2 bd-highlight">
            Current club: {{ player.club.name }}
        </div>
        <div class="p-2 bd-highlight">
            Current national team: {{ player.national.name }}
        </div>
        <div class="p-2 bd-highlight d-flex justify-content-left">
            <a class="btn btn-warning" href="{{ path('app_player_edit', {'id': player.id}) }}">Edit</a>
            {{ include('player/_delete_form.html.twig') }}
        </div>
    </div>
</body>
{% endblock %}