src/Entity/National.php
<?php

namespace App\Entity;

use App\Repository\NationalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NationalRepository::class)]
class National
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 1000)]
    private $flag;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $country;

    #[ORM\Column(type: 'integer')]
    private $total_tournaments;

    #[ORM\Column(type: 'integer')]
    private $won_tournaments;

    #[ORM\Column(type: 'integer')]
    private $total_wins;

    #[ORM\Column(type: 'integer')]
    private $total_loses;

    #[ORM\Column(type: 'integer')]
    private $total_draws;

    #[ORM\OneToMany(mappedBy: 'national', targetEntity: Player::class)]
    private $player;

    public function __construct()
    {
        $this->player = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFlag(): ?string
    {
        return $this->flag;
    }

    public function setFlag(string $flag): self
    {
        $this->flag = $flag;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getTotalTournaments(): ?int
    {
        return $this->total_tournaments;
    }

    public function setTotalTournaments(int $total_tournaments): self
    {
        $this->total_tournaments = $total_tournaments;

        return $this;
    }

    public function getWonTournaments(): ?int
    {
        return $this->won_tournaments;
    }

    public function setWonTournaments(int $won_tournaments): self
    {
        $this->won_tournaments = $won_tournaments;

        return $this;
    }

    public function getTotalWins(): ?int
    {
        return $this->total_wins;
    }

    public function setTotalWins(int $total_wins): self
    {
        $this->total_wins = $total_wins;

        return $this;
    }

    public function getTotalLoses(): ?int
    {
        return $this->total_loses;
    }

    public function setTotalLoses(int $total_loses): self
    {
        $this->total_loses = $total_loses;

        return $this;
    }

    public function getTotalDraws(): ?int
    {
        return $this->total_draws;
    }

    public function setTotalDraws(int $total_draws): self
    {
        $this->total_draws = $total_draws;

        return $this;
    }

    /**
     * @return Collection<int, Player>
     */
    public function getPlayer(): Collection
    {
        return $this->player;
    }

    public function addPlayer(Player $player): self
    {
        if (!$this->player->contains($player)) {
            $this->player[] = $player;
            $player->setNational($this);
        }

        return $this;
    }

    public function removePlayer(Player $player): self
    {
        if ($this->player->removeElement($player)) {
            // set the owning side to null (unless already changed)
            if ($player->getNational() === $this) {
                $player->setNational(null);
            }
        }

        return $this;
    }
}

src/Form/NationalType.php
<?php

namespace App\Form;

use App\Entity\National;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

class NationalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('flag', TextType::class, ['label' => 'Flag icon url ', 'attr' => array('placeholder' => 'link to png file'),
            'constraints' => [new Assert\Callback([
                'callback' => static function(?string $value, ExecutionContextInterface $context){
                    if(!str_ends_with($value, ".png")){
                        $context
                            ->buildViolation('Url must end by ".png"')
                            ->atPath('[flag]')
                            ->addViolation();
                    }
                }
            ]
            )]])
            ->add('name', TextType::class, ['label' => 'Name ', 'attr' => array('placeholder' => 'ex: name')])
            ->add('country', TextType::class, ['label' => 'Representated country ', 'attr' => array('placeholder' => 'ex: country')])
            ->add('total_tournaments', IntegerType::class, ['label' => 'Number of tournaments ', 'attr' => array('placeholder' => 'ex: 0'),
            'constraints' => [
                new Assert\PositiveOrZero([
                    'message' => 'Value must be positive or at least equals to 0.'
                ])]])
            ->add('won_tournaments', IntegerType::class, ['label' => 'Number of won tournaments ', 'attr' => array('placeholder' => 'ex: 0'),
            'constraints' => [
                new Assert\PositiveOrZero([
                    'message' => 'Value must be positive or at least equals to 0.'
                ])]])
            ->add('total_wins', IntegerType::class, ['label' => 'Number of wins until this year ', 'attr' => array('placeholder' => 'ex: 0'),
            'constraints' => [
                new Assert\PositiveOrZero([
                    'message' => 'Value must be positive or at least equals to 0.'
                ])]])
            ->add('total_loses', IntegerType::class, ['label' => 'Number of loses until this year ', 'attr' => array('placeholder' => 'ex: 0'),
            'constraints' => [
                new Assert\PositiveOrZero([
                    'message' => 'Value must be positive or at least equals to 0.'
                ])]])
            ->add('total_draws', IntegerType::class, ['label' => 'Number of draws until this year ', 'attr' => array('placeholder' => 'ex: 0'),
            'constraints' => [
                new Assert\PositiveOrZero([
                    'message' => 'Value must be positive or at least equals to 0.'
                ])]])
            ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => National::class,
        ]);
    }
}

src/Controller/NationalController.php
<?php

namespace App\Controller;

use App\Entity\National;
use App\Form\NationalType;
use App\Repository\NationalRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/national')]
class NationalController extends AbstractController
{
    #[Route('/', name: 'app_national_index', methods: ['GET'])]
    public function index(NationalRepository $nationalRepository): Response
    {
        return $this->render('national/index.html.twig', [
            'nationals' => $nationalRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_national_new', methods: ['GET', 'POST'])]
    public function new(Request $request, NationalRepository $nationalRepository): Response
    {
        $national = new National();
        $form = $this->createForm(NationalType::class, $national);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $nationalRepository->add($national);
            return $this->redirectToRoute('app_national_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('national/new.html.twig', [
            'national' => $national,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_national_show', methods: ['GET'])]
    public function show(National $national): Response
    {
        return $this->render('national/show.html.twig', [
            'national' => $national,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_national_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, National $national, NationalRepository $nationalRepository): Response
    {
        $form = $this->createForm(NationalType::class, $national);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $nationalRepository->add($national);
            return $this->redirectToRoute('app_national_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('national/edit.html.twig', [
            'national' => $national,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_national_delete', methods: ['POST'])]
    public function delete(Request $request, National $national, NationalRepository $nationalRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$national->getId(), $request->request->get('_token'))) {
            $nationalRepository->remove($national);
        }

        return $this->redirectToRoute('app_national_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/national/_delete_form.html.twig
<form method="post" action="{{ path('app_national_delete', {'id': national.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ national.id) }}">
    <button class="btn btn-danger btn-outline-light">Delete</button>
</form>

templates/national/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary btn-outline-light">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/national/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ national.name }}{% endblock %}

{% block body %}
<body style="background-image: url({{ bg }});
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;">

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <h1>Edit national team</h1>
            <a class="navbar-brand" href="{{ path('app_national_index') }}">Back</a>
        </div>
    </nav><br>

    {{ include('national/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('national/_delete_form.html.twig') }}
</body>
{% endblock %}

templates/national/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}National teams{% endblock %}

{% block body %}
<body style="background-image: url({{ bg }});
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;">

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ path('app_index') }}">Home</a>
            <h1>National teams</h1>
            <form class="d-flex" action="{{ path('app_national_new') }}">
                <input class="form-control me-2" type="submit" value="New" />
            </form>
        </div>
    </nav><br>  

    <ul class="list-group list-group-horizontal list-group-flush">
        {% for national in nationals %}
            <li class="list-group-item">
                <div class="card-img-top mx-auto">
                    {% if national.flag is empty %}
                        Unavailable flag
                    {% else %}
                        <img style="width: 10%" class="card-img-top mx-auto" src="{{ national.flag }}"/>
                    {% endif %}
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item bg-transparent">{{ national.name }}</li>
                        <li class="list-group-item bg-transparent">{{ national.country }}</li>
                        <li class="list-group-item bg-transparent">
                            <div class="d-flex justify-content-center">
                                <form action="{{ path('app_national_show', {'id': national.id}) }}">
                                    <input type="submit" value="View" />
                                </form>
                                <form action="{{ path('app_national_edit', {'id': national.id}) }}">
                                    <input type="submit" value="Edit" />
                                </form>
                            </div>
                        </li>
                    </ul>
                </div>
            </li>
        {% endfor %} 
    </ul>
</body>
{% endblock %}

templates/national/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add national team{% endblock %}

{% block body %}
<body style="background-image: url({{ bg }});
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;">

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <h1>Informations about national teams</h1>
            <a class="navbar-brand" href="{{ path('app_national_index') }}">Back</a>
        </div>
    </nav><br>

    {{ include('national/_form.html.twig') }}
</body>
{% endblock %}

templates/national/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ national.name }}{% endblock %}

{% block body %}
<body style="background-image: url({{ bg }});
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;">

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ path('app_national_index') }}">Back</a>
            <h1>Details</h1>
        </div>
    </nav><br>

    <div class="d-flex flex-column bd-highlight mb-3">
        <div class="p-2 bd-highlight">
            <img width='10%' src="{{ national.flag }}"/>
        </div>
        <div class="p-2 bd-highlight">
            Name: {{ national.name }}
        </div>
        <div class="p-2 bd-highlight">
            Country: {{ national.country }}
        </div>
        <div class="p-2 bd-highlight">
            Number of participated tournaments: {{ national.totalTournaments }}
        </div>
        <div class="p-2 bd-highlight">
            Number of won tournaments: {{ national.wonTournaments }}
        </div>
        <div class="p-2 bd-highlight">
            Number of wins: {{ national.totalWins }}
        </div>
        <div class="p-2 bd-highlight">
            Number of loses: {{ national.totalLoses }}
        </div>
        <div class="p-2 bd-highlight">
            Number of draws: {{ national.totalDraws }}
        </div>
        <div class="p-2 bd-highlight d-flex justify-content-left">
            <a class="btn btn-warning" href="{{ path('app_national_edit', {'id': national.id}) }}">Edit</a>
            {{ include('national/_delete_form.html.twig') }}
        </div>
    </div>
</body>
{% endblock %}